name: Reviewers

options:
  deploymentTarget:
    iOS: 17.0
schemes:
  Develop:
    build:
      targets:
        ReviewersDevelop: all
    run:
      config: Debug
    # test:
    #   config: Debug
    #   gatherCoverageData: false
    #   targets:
    #     - name: ReviewersTests
    #       parallelizable: true
    #       randomExecutionOrder: true
    #     - name: ReviewersUITests
    #       parallelizable: true
    #       randomExecutionOrder: true
  # Production:
  #   build:
  #     targets:
  #       ReviewersProduction: all
  #   run:
  #     config: Debug
settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5RH346BQ66
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: 1
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift
    from: 7.4.0
  LicenseList:
    url: https://github.com/cybozu/LicenseList
    from: 0.4.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.24.0
  Markdown:
    url: https://github.com/apple/swift-markdown
    from: 0.3.0
  # SwiftLint:
  #   url: https://github.com/realm/SwiftLint
  #   from: 0.54.0

targets:
  ReviewersDevelop:
    type: application
    platform: iOS
    sources:
      - path: Reviewers
      - path: Config/Develop
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Develop
        # CODE_SIGN_ENTITLEMENTS: Config/Develop/ReviewersDevelop.entitlements
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.reviewers-development
    info:
      path: Reviewers/Info/Info-Develop.plist
      properties:
        UIUserInterfaceStyle: Light
        CFBundleDisplayName: Reviewers
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSCameraUsageDescription: バーコードの読み取りのためカメラを使用します。
        UILaunchScreen:
          UIImageName: splash-logo
          UIColorName: app-splash-background-color
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIRequiresFullScreen: YES
        UIAppFonts:
          - MPLUS2-VariableFont.ttf
        MinimumOSVersion: "17.0"
    dependencies:
      - package: Rswift
        product: RswiftLibrary
      - package: LicenseList
        product: LicenseList
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      # - package: Firebase
      #   product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseStorage
      # - package: Firebase
      #   product: FirebaseMessaging
      - package: Firebase
        product: FirebaseFirestore
      - package: Markdown
        product: Markdown
    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift
      - plugin: PrepareLicenseList
        package: LicenseList
    # postBuildScripts:
    #   - script: "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
    #     name: Crashlytics
    #     basedOnDependencyAnalysis: false
    #     inputFiles:
    #       - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
    #       - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  # ReviewersProduction:
  #   type: application
  #   platform: iOS
  #   sources:
  #     - path: Reviewers
  #     - path: Config/Production
  #   settings:
  #     base:
  #       ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Production
  #       CODE_SIGN_ENTITLEMENTS: Config/Production/ReviewersProduction.entitlements
  #       DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  #       PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.it        
  #   info:
  #     path: Reviewers/Info/Info-Production.plist
  #     properties:
  #       Appearance: Light
  #       CFBundleDisplayName: Reviewers
  #       CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  #       CFBundleShortVersionString: $(MARKETING_VERSION)
  #       UILaunchScreen:
  #         UIColorName: thema-light-gray
  #       UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
  #       UIRequiresFullScreen: YES
  #       UIAppFonts:
  #         - MPLUS2-VariableFont.ttf
  #       MinimumOSVersion: "17.0"
  #   dependencies:
  #     - package: Rswift
  #       product: RswiftLibrary
  #     - package: LicenseList
  #       product: LicenseList
  #     - package: Firebase
  #       product: FirebaseAnalytics
  #     - package: Firebase
  #       product: FirebaseAuth
  #     - package: Firebase
  #       product: FirebaseCrashlytics
  #     - package: Firebase
  #       product: FirebaseStorage
  #     - package: Firebase
  #       product: FirebaseMessaging
  #     - package: Firebase
  #       product: FirebaseFirestore
  #     - package: Markdown
  #       product: Markdown
  #   buildToolPlugins:
  #     - plugin: RswiftGenerateInternalResources
  #       package: Rswift
  #     - plugin: PrepareLicenseList
  #       package: LicenseList
  #   postBuildScripts:
  #     - script: "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
  #       name: Crashlytics
  #       basedOnDependencyAnalysis: false
  #       inputFiles:
  #         - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
  #         - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  # ReviewersTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources:
  #     - ReviewersTests
  #   dependencies:
  #     - target: ReviewersDevelop
  # ReviewersUITests:
  #   type: bundle.ui-testing
  #   platform: iOS
  #   sources:
  #     - ReviewersUITests
  #   dependencies:
  #     - target: ReviewersDevelop





# name: Reviewers
# options:
#   deploymentTarget:
#     iOS: 17.0
#   postGenCommand: bundle exec pod install

# packages:
#   R.swift:
#     url: https://github.com/mac-cain13/R.swift
#     from: 5.4.0
#   SDWebImageSwiftUI:
#     url: https://github.com/SDWebImage/SDWebImageSwiftUI.git
#     from: 2.0.2

# settings:
#   base:
#     CODE_SIGN_STYLE: Automatic
#     DEVELOPMENT_TEAM: 5RH346BQ66
#     MARKETING_VERSION: 3.0.0


# schemes:
#   ReviewersDevelop:
#     type: application
#     sources:
#       - path: Reviewers
#       - path: Config/Develop
#     settings:
#       base:
#         ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Develop
#         CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
#         DEBUG_INFORMATION_FORMAT: dwarf-with-dsymm
#         PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.sandbox.charalarm
#       info:
#         path: Reviewers/Info/Info-Develop.plist
#         CFBundleDisplayName: Reviewers





#     build:
#       targets:
#         Reviewers-local: all
#     run:
#       config: Debug
#     test:
#       config: Debug
#       gatherCoverageData: false
#       targets:
#         - name: ReviewersTests
#           parallelizable: true
#           randomExecutionOrder: true
#   fp-production:
#     build:
#       targets:
#         fp-production: all
#     run:
#       config: Debug
#   chemist-production:
#     build:
#       targets:
#         chemist-production: all
#     run:
#       config: Debug

# targets:
#   Reviewers-local:
#     type: application
#     platform: iOS
#     deploymentTarget: "14.0"
#     sources:
#       - path: Reviewers
#     settings:
#       base:
#         PRODUCT_BUNDLE_IDENTIFIER: jp.Reviewers.local
#         INFOPLIST_FILE: Reviewers/Info.plist
#         CURRENT_PROJECT_VERSION: 1
#         TARGETED_DEVICE_FAMILY: 1
#         ASSETCATALOG_COMPILER_APPICON_NAME: icon-local
#         SWIFT_OPTIMIZATION_LEVEL: -Onone
#       configs:
#         Debug:
#           DISPLAY_NAME: 理科子Local
#           GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
#           ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
#         Release:
#           DISPLAY_NAME: 理科子Local
#           GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
#           ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
#     dependencies:
#       - package: R.swift.Library
#         product: Rswift
#       - package: SDWebImageSwiftUI
#         product: SDWebImageSwiftUI
#   fp-production:
#     type: application
#     platform: iOS
#     deploymentTarget: "14.0"
#     sources:
#       - path: Reviewers
#     dependencies:
#       - package: R.swift.Library
#         product: Rswift
#     preBuildScripts:
#       - script: ./Scripts/BuildPhases/rswift.sh
#         name: R.swift
#         inputFiles:
#           - $TEMP_DIR/rswift-lastrun
#         outputFiles:
#           - $SRCROOT/Reviewers/Generated/R.generated.swift
#     settings:
#       base:
#         PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.fp
#         INFOPLIST_FILE: Reviewers/Info.plist
#         CURRENT_PROJECT_VERSION: 1
#         TARGETED_DEVICE_FAMILY: 1
#         ASSETCATALOG_COMPILER_APPICON_NAME: icon-fp-production
#         SWIFT_OPTIMIZATION_LEVEL: -Onone
#       configs:
#         Debug:
#           DISPLAY_NAME: FPアプリ
#           GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
#           ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
#         Release:
#           DISPLAY_NAME: FPアプリ
#           GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
#           ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
#     dependencies:
#       - package: R.swift.Library
#         product: Rswift
#       - package: SDWebImageSwiftUI
#         product: SDWebImageSwiftUI
#   chemist-production:
#     type: application
#     platform: iOS
#     deploymentTarget: "14.0"
#     sources:
#       - path: Reviewers
#     dependencies:
#       - package: R.swift.Library
#         product: Rswift
#     preBuildScripts:
#       - script: ./Scripts/BuildPhases/rswift.sh
#         name: R.swift
#         inputFiles:
#           - $TEMP_DIR/rswift-lastrun
#         outputFiles:
#           - $SRCROOT/Reviewers/Generated/R.generated.swift
#     settings:
#       base:
#         PRODUCT_BUNDLE_IDENTIFIER: jp.conol.chemist
#         INFOPLIST_FILE: Reviewers/Info.plist
#         CURRENT_PROJECT_VERSION: 1
#         TARGETED_DEVICE_FAMILY: 1
#         ASSETCATALOG_COMPILER_APPICON_NAME: icon-chemist-production
#         SWIFT_OPTIMIZATION_LEVEL: -Onone
#       configs:
#         Debug:
#           DISPLAY_NAME: ４択化学
#           GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
#           ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
#         Release:
#           DISPLAY_NAME: ４択化学
#           GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
#           ADMOB_UNIT_ID: ca-app-pub-3940256099942544/2934735716
#     dependencies:
#       - package: R.swift.Library
#         product: Rswift
#       - package: SDWebImageSwiftUI
#         product: SDWebImageSwiftUI
#   ReviewersTests:
#     type: bundle.unit-test
#     platform: iOS
#     sources:
#       - ReviewersTests
#     settings:
#       base:
#         INFOPLIST_FILE: ReviewersTests/Info.plist
#     dependencies:
#       - target: Reviewers-local
#   ReviewersUITests:
#     type: bundle.ui-testing
#     platform: iOS
#     sources:
#       - ReviewersUITests
#     settings:
#       base:
#         INFOPLIST_FILE: ReviewersUITests/Info.plist
#     dependencies:
#       - target: Reviewers-local
